### register
POST http://localhost:3003/user/register
Content-Type: application/json

{
    "firstName":"Ngatia", 
    "lastName": "Motsoaledi", 
    "userName": "ngatia", 
    "email":"ngatia25@gmail.com", 
    "password":"12345678", 
    "phoneNumber": "12345678"
}


### login
POST  http://localhost:3003/user/login
Content-Type: application/json

{
    "email":"ngatia25@gmail.com", 
    "password":"12345678"
}


###Translate Language
POST http://localhost:3003/saveLanguage/612189bc-5300-4423-b57a-dc32313e7797
Content-Type: application/json

{
    "sourceText" : "This is a sample text to translate and save",
    "targetLanguage" : "sp", // French
    "translatedText " : "Este es un texto de muestra para traducir y guardar."
}